server:
  port: 8401

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8102}/eureka/

spring:
  boot:
    admin:
      client:
        url: http://localhost:8101

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

