server:
  port: 8100

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fibers/demo-spring-cloud-config-repository.git
  boot:
    admin:
      client:
        url: http://localhost:8101

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

